version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pass@123
      MYSQL_USER: sammy
      MYSQL_PASSWORD: Pass@123
      MYSQL_DATABASE: matw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./static/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql_data:
